name: atomi_architecture
description: Internship Evaluation
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1

  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  equatable: ^2.0.5
  get: ^4.6.6
  injectable: ^2.4.2
  logger: ^2.4.0
  json_annotation: ^4.9.0
  retrofit: ^4.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  get_it: ^7.7.0
  skeletonizer: ^1.4.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - asset/image/
    - asset/icon/
    - asset/gif/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
